server:
  port: 9080

spring:
  application:
    name: msvc-producto
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=LA_CANTERA;trustServerCertificate=true
    username: Algoritmo
    password: 12345

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka