eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cargo
          uri: lb://msvc-cargo
          predicates:
            - Path=/api/cargo/**
        - id: turno
          uri: lb://msvc-turno
          predicates:
            - Path=/api/turno/**
        - id: mesa
          uri: lb://msvc-mesa
          predicates:
            - Path=/api/mesa/**
        - id: delivery
          uri: lb://msvc-delivery
          predicates:
            - Path=/api/delivery/**
        - id: formapago
          uri: lb://msvc-formapago
          predicates:
            - Path=/api/formapago/**
        - id: categoria
          uri: lb://msvc-categoria
          predicates:
            - Path=/api/categoriaproducto/**
        - id: adicional
          uri: lb://msvc-adicional
          predicates:
            - Path=/api/adicional/**
        - id: producto
          uri: lb://msvc-producto
          predicates:
            - Path=/api/producto/**
        - id: insumo
          uri: lb://msvc-insumo
          predicates:
            - Path=/api/insumo/**
        - id: categoriainsumo
          uri: lb://msvc-categoriainsumo
          predicates:
            - Path=/api/categoriainsumo/**
        - id: pedido
          uri: lb://msvc-pedido
          predicates:
            - Path=/api/pedido/**
        - id: comprobante
          uri: lb://msvc-comprobante
          predicates:
            - Path=/api/comprobante/**
        - id: cocina
          uri: lb://msvc-cocina
          predicates:
            - Path=/api/cocina/**
        - id: inventario
          uri: lb://msvc-cocina
          predicates:
            - Path=/api/inventario/**
        - id: caja
          uri: lb://msvc-cocina
          predicates:
            - Path=/api/caja/**
        - id: proveedor
          uri: lb://msvc-proveedor
          predicates:
            - Path=/api/proveedor/**
        - id: privilegio
          uri: lb://msvc-privilegio
          predicates:
            - Path=/api/privilegio/**
        - id: usuario
          uri: lb://msvc-usuario
          predicates:
            - Path=/api/usuario/**
        - id: empleado
          uri: lb://msvc-empleado
          predicates:
            - Path=/api/empleado/**